---
changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot[bot]
      - renovate[bot]
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
        - feat
    - title: Bug Fixes
      labels:
        - fix
        - bug
    - title: Performance Improvements
      labels:
        - perf
        - performance
    - title: Refactoring
      labels:
        - refactor
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: Tests & Build
      labels:
        - test
        - build
        - ci
    - title: Other Changes
      labels:
        - "*"
